### ISSUE TITLE
消费者调用失败，No provider available for the service

### ISSUE THREAD

**Issue by HScarb** [tonyruiyu/dubbo-mock#7]
## 现象

本地启动项目并注册服务和方法，使用dubbo调用该方法，报错
` Failed to check the status of the service com.scarb.test.TestService. No provider available for the service com.scarb.test.TestService from the url zookeeper://127.0.0.1:2181/com.alibaba.dubbo.registry.RegistryService?application=app&dubbo=2.5.3&interface=com.scarb.test.TestService&methods=testString&pid=8300&side=consumer&timestamp=1553619744776 to the consumer 10.0.75.1 use dubbo version 2.5.3`

### 注册服务提供者

在本地用启动项目web端，注册了一个服务并添加一个Mock方法，如图。
![Snipaste_2019-03-27_01-10-11](https://user-images.githubusercontent.com/10664298/55018156-3259b100-502d-11e9-80a3-b3c128afb1a4.png)
![Snipaste_2019-03-27_01-10-28](https://user-images.githubusercontent.com/10664298/55018141-2d94fd00-502d-11e9-91c8-7bf1f6026ad8.png)
打印日志
```log
2019-03-27 01:01:43,374 INFO [com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry,http-nio-8088-exec-1] - < [DUBBO] Register: dubbo://10.0.75.1:8788/com.scarb.test.TestService?anyhost=true&application=app&dubbo=2.5.3&generic=true&group=group&interface=com.scarb.test.TestService&methods=*&pid=4060&retries=5&side=provider&timeout=50000&timestamp=1553619703373, dubbo version: 2.5.3, current host: 127.0.0.1>
2019-03-27 01:01:43,383 INFO [com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry,http-nio-8088-exec-1] - < [DUBBO] Subscribe: provider://10.0.75.1:8788/com.scarb.test.TestService?anyhost=true&application=app&category=configurators&check=false&dubbo=2.5.3&generic=true&group=group&interface=com.scarb.test.TestService&methods=*&pid=4060&retries=5&side=provider&timeout=50000&timestamp=1553619703373, dubbo version: 2.5.3, current host: 127.0.0.1>
2019-03-27 01:01:43,389 INFO [com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry,http-nio-8088-exec-1] - < [DUBBO] Notify urls for subscribe url provider://10.0.75.1:8788/com.scarb.test.TestService?anyhost=true&application=app&category=configurators&check=false&dubbo=2.5.3&generic=true&group=group&interface=com.scarb.test.TestService&methods=*&pid=4060&retries=5&side=provider&timeout=50000&timestamp=1553619703373, urls: [empty://10.0.75.1:8788/com.scarb.test.TestService?anyhost=true&application=app&category=configurators&check=false&dubbo=2.5.3&generic=true&group=group&interface=com.scarb.test.TestService&methods=*&pid=4060&retries=5&side=provider&timeout=50000&timestamp=1553619703373], dubbo version: 2.5.3, current host: 127.0.0.1>
```

### 用消费者调用

实现`TestService`接口

```java
package com.scarb.test;

public interface TestService {
    String testString();
}
```

然后编写消费者如下

```java
import com.alibaba.dubbo.config.ApplicationConfig;
import com.alibaba.dubbo.config.ReferenceConfig;
import com.alibaba.dubbo.config.RegistryConfig;
import com.alibaba.dubbo.rpc.service.GenericService;
import com.scarb.test.TestService;

public class MockTestConsumer {

    private static TestService testService;

    public static void main(String[] args) throws Exception{
        ApplicationConfig application = new ApplicationConfig();
        application.setName("app");

        RegistryConfig registry = new RegistryConfig();
        registry.setAddress("zookeeper://127.0.0.1:2181");
        registry.setGroup("group");

        application.setRegistry(registry);

        ReferenceConfig<GenericService> reference = new ReferenceConfig<GenericService>();
        // 弱类型接口名
        reference.setInterface(TestService.class);
        reference.setApplication(application);

        TestService testService = (TestService) reference.get();
        System.out.println(testService.testString());
    }
}
```

用该程序尝试调用Mock接口，报错，如下

```log
[27/03/19 01:02:33:033 CST] main-SendThread(activate.navicat.com:2181)  INFO zookeeper.ClientCnxn: Socket connection established to activate.navicat.com/127.0.0.1:2181, initiating session
[27/03/19 01:02:33:033 CST] main-SendThread(activate.navicat.com:2181)  INFO zookeeper.ClientCnxn: Session establishment complete on server activate.navicat.com/127.0.0.1:2181, sessionid = 0x100058eef05001c, negotiated timeout = 30000
[27/03/19 01:02:33:033 CST] main-EventThread  INFO zkclient.ZkClient: zookeeper state changed (SyncConnected)
[27/03/19 01:02:33:033 CST] main  INFO zookeeper.ZookeeperRegistry:  [DUBBO] Register: consumer://10.0.75.1/com.scarb.test.TestService?application=app&category=consumers&check=false&dubbo=2.5.3&interface=com.scarb.test.TestService&methods=testString&pid=8300&side=consumer&timestamp=1553619744776, dubbo version: 2.5.3, current host: 10.0.75.1
[27/03/19 01:02:33:033 CST] main  INFO zookeeper.ZookeeperRegistry:  [DUBBO] Subscribe: consumer://10.0.75.1/com.scarb.test.TestService?application=app&category=providers,configurators,routers&dubbo=2.5.3&interface=com.scarb.test.TestService&methods=testString&pid=8300&side=consumer&timestamp=1553619744776, dubbo version: 2.5.3, current host: 10.0.75.1
[27/03/19 01:02:34:034 CST] main  INFO zookeeper.ZookeeperRegistry:  [DUBBO] Notify urls for subscribe url consumer://10.0.75.1/com.scarb.test.TestService?application=app&category=providers,configurators,routers&dubbo=2.5.3&interface=com.scarb.test.TestService&methods=testString&pid=8300&side=consumer&timestamp=1553619744776, urls: [empty://10.0.75.1/com.scarb.test.TestService?application=app&category=providers&dubbo=2.5.3&interface=com.scarb.test.TestService&methods=testString&pid=8300&side=consumer&timestamp=1553619744776, empty://10.0.75.1/com.scarb.test.TestService?application=app&category=configurators&dubbo=2.5.3&interface=com.scarb.test.TestService&methods=testString&pid=8300&side=consumer&timestamp=1553619744776, empty://10.0.75.1/com.scarb.test.TestService?application=app&category=routers&dubbo=2.5.3&interface=com.scarb.test.TestService&methods=testString&pid=8300&side=consumer&timestamp=1553619744776], dubbo version: 2.5.3, current host: 10.0.75.1
Exception in thread "main" java.lang.IllegalStateException: Failed to check the status of the service com.scarb.test.TestService. No provider available for the service com.scarb.test.TestService from the url zookeeper://127.0.0.1:2181/com.alibaba.dubbo.registry.RegistryService?application=app&dubbo=2.5.3&interface=com.scarb.test.TestService&methods=testString&pid=8300&side=consumer&timestamp=1553619744776 to the consumer 10.0.75.1 use dubbo version 2.5.3
	at com.alibaba.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:420)
	at com.alibaba.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:300)
	at com.alibaba.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:138)
	at MockTestConsumer.main(MockTestConsumer.java:25)
```

## 求助

试了很久始终无法成功调用mock，所以求助
是调用方法错误还是其他问题？
能否提供成功调用Mock的示例？

**Comment by tonyruiyu** [comment]
你写的调用客户端有问题，不是给注册中心给group 而是给service group ，你仔细看看你的代码，你配置是有group的。但是你调用没有指定。2中方式可以解决，要么你不要配置group。要么你调用的时候正确的指定group到service上

**Comment by tonyruiyu** [comment]
而且你这个设置了版本  service(reference)上   也要指定

**Comment by HScarb** [comment]
不配置group和version后问题已经解决，非常感谢！
